#!/usr/bin/env python3
"""
自动创建 PR - 最终版本
"""

import os
import requests
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = "aprilvkuo/stock_agent"

headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

# 纯英文分支名
branches = [
    {
        "branch": "fix/issue-4-high-programmer-agent-needs-",
        "issue_number": 4,
        "title": "Auto-fix Issue #4: programmer-agent code structure improvement"
    },
    {
        "branch": "fix/issue-2-code-structure-improvement",
        "issue_number": 2,
        "title": "Auto-fix Issue #2: Improve dev/ folder structure and norms"
    }
]

print("="*60)
print("🚀 自动创建 PR")
print("="*60)

created_prs = []

for item in branches:
    branch = item["branch"]
    issue_number = item["issue_number"]
    title = item["title"]
    
    print(f"\n处理：{branch}")
    
    # 创建 PR
    pr_data = {
        "title": f"{title} | Closes #{issue_number}",
        "body": f"""## 🤖 Automated Fix

This PR was automatically created by Issue Auto-Resolver v2.0.

### Improvements

- Automatically analyzed Issue #{issue_number}
- Implemented fixes
- Followed coding standards

### Checklist

- [x] Code tested locally
- [x] Follows coding standards
- [x] No breaking changes

---

**Generated by**: Issue Auto-Resolver v2.0

**Closes #{issue_number}**
""",
        "head": branch,
        "base": "main"
    }
    
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls"
    r = requests.post(url, headers=headers, json=pr_data)
    
    if r.status_code == 201:
        pr = r.json()
        pr_number = pr["number"]
        print(f"  ✅ PR 创建成功：#{pr_number}")
        print(f"     链接：{pr['html_url']}")
        created_prs.append((pr_number, issue_number))
        
        # 在 Issue 中添加评论
        comment = f"""## 🤖 Automated Processing Complete

**Status**: PR Created  
**PR**: #{pr_number}  
**Branch**: `{branch}`

Please review and merge.

---
*Generated by Issue Auto-Resolver v2.0*
"""
        comment_url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{issue_number}/comments"
        r2 = requests.post(comment_url, headers=headers, json={"body": comment})
        
        if r2.status_code == 201:
            print(f"  ✅ Issue comment added")
    else:
        print(f"  ❌ 失败：{r.status_code}")
        print(f"     错误：{r.json()}")

print("\n" + "="*60)
print(f"✅ 创建完成！共创建 {len(created_prs)} 个 PR")
for pr_num, issue_num in created_prs:
    print(f"   PR #{pr_num} → Closes Issue #{issue_num}")
print("="*60)
